# Generated by Django 5.0 on 2025-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinfo',
            old_name='twiter_url',
            new_name='twitter_url',
        ),
    ]
