# Generated by Django 5.0 on 2025-02-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_testimonials_rating_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
