# Generated by Django 5.0 on 2025-02-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_frequentlyaskedquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequentlyAskedQuestions',
            new_name='FrequentlyAskedQuestion',
        ),
    ]
