# Generated by Django 5.0 on 2025-02-08 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
